// RawSec — copy
export const RAWSEC_DATA = {
  nav: { links: [
    { id: 'servicios', label: 'Servicios' },
    { id: 'proceso', label: 'Proceso' },
    { id: 'proyecto', label: 'I+D' },
    { id: 'equipo', label: 'Equipo' },
    { id: 'clientes', label: 'Clientes' },
  ], cta: 'Agendar reunión' },
  hero: {
    eyebrow: 'Desarrollo seguro · Pentesting · Cumplimiento',
    h1a: ['Software que nace', 'seguro.'],
    h1b: 'Seguridad y desarrollo sin concesiones.',
    h1c: ['Construido a medida.', 'Blindado por diseño.'],
    sub: 'Desarrollo full-stack y auditorías de ciberseguridad bajo un mismo equipo. Construimos tu plataforma y la blindamos — sin dejar la seguridad para el final.',
    cta1: 'Agendar reunión', cta2: 'Ver servicios',
    badges: ['eJPT', 'eWPTX', 'CCNA', 'AWS Cloud Practitioner'],
    term: [
      { t: 'cmd', s: 'rawsec init --cliente "tu-empresa.cl"' },
      { t: 'ok', s: '✓ stack: next.js + postgresql' },
      { t: 'cmd', s: 'rawsec audit --scope web,api,red' },
      { t: 'out', s: '  escaneando superficies de ataque…' },
      { t: 'ok', s: '✓ 0 vulnerabilidades críticas' },
      { t: 'cmd', s: 'rawsec deploy --hardened' },
      { t: 'ok', s: '✓ producción · monitoreo activo' },
    ],
    coords: 'SANTIAGO, CHILE · 33.4489°S 70.6693°W',
  },
  strip: ['Desarrollo full-stack', 'Pentesting certificado', 'Ley 21.719 · Chile', 'Arquitectura cloud', 'Hardening de redes', 'Automatización', 'Machine Learning', 'Agentes RAG', 'LLMs', 'Visión computacional', 'Red Team', 'Forense digital', 'CCNA · Redes', 'AWS Security', 'Sistemas ISP', 'Pasarelas de pago', 'Dashboards financieros', 'Arquitectura de software', 'Diseño de bases de datos', 'Diagramas UML', 'Modelado relacional', 'Microservicios', 'Hardening de servidores', 'Seguridad AWS', 'Firewall & ACLs', 'Segmentación de redes', 'IAM & VPC'],
  services: {
    label: '01 — servicios', title: 'Dos disciplinas, un equipo.',
    sub: 'La mayoría desarrolla primero y asegura después. Nosotros hacemos ambas cosas a la vez.',
    items: [
      { icon: 'code', title: 'Software a medida',
        desc: 'Construimos la solución digital exacta para tu negocio: apps web, SaaS, e-commerce e integraciones con stack moderno.',
        li: ['Aplicaciones web y SaaS', 'LMS y e-commerce con pagos locales', 'Integraciones y automatización de APIs'] },
      { icon: 'shield', title: 'Ciberseguridad ofensiva',
        desc: 'Auditorías y pentesting con metodología certificada. Encontramos las brechas antes que un atacante.',
        li: ['Pentesting web y de infraestructura', 'Auditorías de seguridad y hardening', 'Redes (CCNA) y cloud (AWS)'] },
      { icon: 'scale', title: 'Cumplimiento y datos',
        desc: 'Preparamos tu empresa para la Ley 21.719 de protección de datos personales, con evidencia auditable.',
        li: ['Diagnóstico de brechas normativas', 'Políticas y gestión de datos', 'Automatización del cumplimiento'] },
      { icon: 'brain', title: 'IA Aplicada',
        desc: 'Chatbots conversacionales, pipelines de Machine Learning y agentes RAG con modelos locales o en la nube.',
        li: ['Chatbots RAG con LangChain + ChromaDB', 'Clasificación y predicción con ML supervisado', 'Modelos locales (Llama 3) y API GPT'] },
      { icon: 'card', title: 'Pagos e Integraciones',
        desc: 'Integración de pasarelas de pago chilenas e internacionales, con flujos completos de cobro y conciliación.',
        li: ['Webpay / Transbank y Banchile Pagos', 'MercadoPago y Getnet REST API', 'Flujos de pago, refund y conciliación'] },
      { icon: 'layers', title: 'Software para empresas',
        desc: 'Sistemas de gestión complejos — ISP, salud, educación — con arquitectura documentada y despliegue escalable.',
        li: ['Arquitectura 4+1 y SCRUM++', 'WebSocket, Redis y colas en tiempo real', 'NGINX + Docker + Linux (Arch/Ubuntu)'] },
      { icon: 'arch', title: 'Arquitectura de software',
        desc: 'Diseñamos la estructura de tu sistema antes de escribir la primera línea: diagramas de componentes, despliegue, secuencia y planificación técnica.',
        li: ['Diagramas de componentes, secuencia y despliegue', 'Microservicios, monolitos y arquitectura en capas', 'Planificación técnica documentada'] },
      { icon: 'database', title: 'Bases de datos',
        desc: 'Modelado relacional y NoSQL desde cero: diagramas ER, modelo físico, normalización y consultas optimizadas para sistemas de alta carga.',
        li: ['Modelado ER, físico y relacional', 'PostgreSQL, MySQL, MongoDB, Redis', 'Optimización de queries e índices'] },
      { icon: 'network', title: 'Hardening de redes',
        desc: 'Configuración segura de infraestructura de red bajo estándar CCNA: routers, switches, firewalls y VPNs protegidos desde la base.',
        li: ['Configuración segura de routers y switches', 'Firewall rules, ACLs y segmentación de redes', 'VPNs, monitoreo y hardening perimetral'] },
      { icon: 'cloud', title: 'Seguridad en cloud',
        desc: 'Auditoría y endurecimiento de entornos AWS: identidades, redes, almacenamiento y trazabilidad configurados para resistir ataques.',
        li: ['Revisión de IAM roles y políticas', 'Segmentación VPC y grupos de seguridad', 'S3 policies, CloudTrail y alertas de auditoría'] },
    ],
  },
  process: {
    label: '02 — proceso', title: 'DevSecOps: seguridad en cada vuelta.',
    sub: 'Nuestro ciclo integra seguridad en las 8 fases del desarrollo — no como auditoría final, sino como parte del flujo.',
    steps: [
      { n: 'Planificar', d: 'Modelado de amenazas desde el diseño' },
      { n: 'Codificar', d: 'Revisión de código y prácticas seguras' },
      { n: 'Construir', d: 'Dependencias verificadas y firmadas' },
      { n: 'Probar', d: 'SAST/DAST + pentesting interno' },
      { n: 'Lanzar', d: 'Gates de seguridad antes de cada release' },
      { n: 'Desplegar', d: 'Infraestructura endurecida (hardening)' },
      { n: 'Operar', d: 'Gestión de accesos y secretos' },
      { n: 'Monitorear', d: 'Alertas, logs y respuesta a incidentes' },
    ],
  },
  project: {
    label: '03 — i+d', tag: 'En desarrollo · acceso anticipado',
    title: 'Cumplimiento Ley 21.719, automatizado.',
    desc: 'Estamos construyendo un agente de cumplimiento que evalúa, documenta y monitorea la adecuación de tu empresa a la nueva ley chilena de protección de datos personales — con tus datos siempre en tu infraestructura.',
    points: ['Datos 100% locales: nada sale de tu empresa', 'Evidencia y reportes auditables', 'Monitoreo continuo de brechas normativas'],
    cta: 'Quiero acceso anticipado',
    cdLabel: 'para la entrada en vigencia de la ley', cdDate: '01 · DIC · 2026',
    cdUnits: ['días', 'horas', 'min'],
  },
  team: {
    label: '04 — equipo', title: 'Los fundadores.',
    sub: 'Un perfil construye, el otro ataca. Juntos cubren el ciclo completo.',
    members: [
      { ini: 'EC', name: 'Emilio Castillo Schmidt', role: 'Co-fundador · Tech Lead',
        bio: 'Arquitectura y desarrollo full-stack. Estudiante de Ingeniería Civil Informática (UNAB). Lidera la construcción de cada plataforma: del diseño del sistema al despliegue.',
        chips: ['Next.js / Node.js', 'PostgreSQL / Supabase', 'Docker / Linux', 'IA aplicada'], certs: [] },
      { ini: 'CR', name: 'Cristóbal Aracena García', role: 'Co-fundador · Security Lead',
        bio: 'Especialista en seguridad ofensiva y defensiva. Estudiante de Bachelor in Computer Science. Pentesting, auditorías de red y administración de infraestructura corporativa.',
        chips: [], certs: ['eJPT', 'eWPTX', 'CCNA', 'AWS Cloud Practitioner'] },
    ],
  },
  quotes: {
    label: '05 — clientes', title: 'Confían en RawSec.',
    items: [
      { q: 'La experiencia 360° cambió la forma en que mostramos los terrenos. Los clientes recorren el proyecto sin moverse de su casa.', who: 'Equipo comercial', org: 'Mar y Cielo · inmobiliaria' },
      { q: 'Necesitaba presencia digital profesional y el resultado fue impecable, en tiempo y forma.', who: 'Psicóloga clínica', org: 'Consulta privada · Santiago' },
      { q: 'Automatizaron el flujo entre nuestro software de gestión y el SII, además de estructurar dos años de datos contables con claridad. Trabajo riguroso y de alto impacto.', who: 'Gerencia', org: 'Inmobiliaria Dominga Norte · La Serena' },
      { q: 'Registraron el dominio corporativo y configuraron cada usuario con sus permisos específicos. Todo el equipo quedó centralizado, controlado y sin accesos de más.', who: 'CEO & Founder', org: 'Minox' },
    ],
    clientsStrip: ['KikiBrows · LMS & e-commerce', 'Mar y Cielo · Inmobiliaria', 'Landing Portafolio Psicológia · La Serena', 'Dominga Norte · Finanzas', 'Minox · Infraestructura TI'],
  },
  contact: {
    label: '06 — contacto', title: '¿Conversamos?',
    sub: 'Cuéntanos qué necesitas construir — o qué necesitas proteger. Respondemos dentro de 24 horas.',
    cta1: 'Agendar reunión', copied: '✓ copiado',
    mailSubject: 'Reunión — RawSec Solutions',
  },
  footer: {
    tagline: 'Desarrollo seguro desde Santiago, Chile.',
    rights: '© 2026 RawSec Solutions',
    links: [{ label: 'GitHub', href: 'https://github.com/RawSecSolutions' }, { label: 'rawsecsolutions@gmail.com', href: 'mailto:rawsecsolutions@gmail.com' }],
  },
};

export const RAWSEC_EMAIL = 'rawsecsolutions@gmail.com';
