// RawSec — copy & i18n (ES/EN)
export const RAWSEC_I18N = {
  es: {
    nav: { links: [
      { id: 'servicios', label: 'Servicios' },
      { id: 'proceso', label: 'Proceso' },
      { id: 'proyecto', label: 'I+D' },
      { id: 'equipo', label: 'Equipo' },
      { id: 'clientes', label: 'Clientes' },
    ], cta: 'Agendar reunión' },
    hero: {
      eyebrow: 'Desarrollo seguro · Pentesting · Cumplimiento',
      h1a: ['Software que nace', 'seguro.'],
      h1b: 'Seguridad y desarrollo sin concesiones.',
      h1c: ['Construido a medida.', 'Blindado por diseño.'],
      sub: 'Desarrollo full-stack y auditorías de ciberseguridad bajo un mismo equipo. Construimos tu plataforma y la blindamos — sin dejar la seguridad para el final.',
      cta1: 'Agendar reunión', cta2: 'Ver servicios',
      badges: ['eJPT', 'eWPTX · en curso', 'CCNA', 'AWS Cloud Practitioner'],
      term: [
        { t: 'cmd', s: 'rawsec init --cliente "tu-empresa.cl"' },
        { t: 'ok', s: '✓ stack: next.js + postgresql' },
        { t: 'cmd', s: 'rawsec audit --scope web,api,red' },
        { t: 'out', s: '  escaneando superficies de ataque…' },
        { t: 'ok', s: '✓ 0 vulnerabilidades críticas' },
        { t: 'cmd', s: 'rawsec deploy --hardened' },
        { t: 'ok', s: '✓ producción · monitoreo activo' },
      ],
      coords: 'SANTIAGO, CHILE · 33.4489°S 70.6693°W',
    },
    strip: ['Desarrollo full-stack', 'Pentesting certificado', 'Ley 21.719 · Chile', 'Arquitectura cloud', 'Hardening de redes', 'Automatización', 'Machine Learning', 'Agentes RAG', 'LLMs', 'Visión computacional', 'Red Team', 'Forense digital', 'CCNA · Redes', 'AWS Security', 'Sistemas ISP', 'Pasarelas de pago', 'Dashboards financieros', 'Arquitectura de software', 'Diseño de bases de datos', 'Diagramas UML', 'Modelado relacional', 'Microservicios', 'Hardening de servidores', 'Seguridad AWS', 'Firewall & ACLs', 'Segmentación de redes', 'IAM & VPC'],
    services: {
      label: '01 — servicios', title: 'Dos disciplinas, un equipo.',
      sub: 'La mayoría desarrolla primero y asegura después. Nosotros hacemos ambas cosas a la vez.',
      items: [
        { icon: 'code', title: 'Software a medida',
          desc: 'Construimos la solución digital exacta para tu negocio: apps web, SaaS, e-commerce e integraciones con stack moderno.',
          li: ['Aplicaciones web y SaaS', 'LMS y e-commerce con pagos locales', 'Integraciones y automatización de APIs'] },
        { icon: 'shield', title: 'Ciberseguridad ofensiva',
          desc: 'Auditorías y pentesting con metodología certificada. Encontramos las brechas antes que un atacante.',
          li: ['Pentesting web y de infraestructura', 'Auditorías de seguridad y hardening', 'Redes (CCNA) y cloud (AWS)'] },
        { icon: 'scale', title: 'Cumplimiento y datos',
          desc: 'Preparamos tu empresa para la Ley 21.719 de protección de datos personales, con evidencia auditable.',
          li: ['Diagnóstico de brechas normativas', 'Políticas y gestión de datos', 'Automatización del cumplimiento'] },
        { icon: 'brain', title: 'IA Aplicada',
          desc: 'Chatbots conversacionales, pipelines de Machine Learning y agentes RAG con modelos locales o en la nube.',
          li: ['Chatbots RAG con LangChain + ChromaDB', 'Clasificación y predicción con ML supervisado', 'Modelos locales (Llama 3) y API GPT'] },
        { icon: 'card', title: 'Pagos e Integraciones',
          desc: 'Integración de pasarelas de pago chilenas e internacionales, con flujos completos de cobro y conciliación.',
          li: ['Webpay / Transbank y Banchile Pagos', 'MercadoPago y Getnet REST API', 'Flujos de pago, refund y conciliación'] },
        { icon: 'layers', title: 'Software para empresas',
          desc: 'Sistemas de gestión complejos — ISP, salud, educación — con arquitectura documentada y despliegue escalable.',
          li: ['Arquitectura 4+1 y SCRUM++', 'WebSocket, Redis y colas en tiempo real', 'NGINX + Docker + Linux (Arch/Ubuntu)'] },
        { icon: 'arch', title: 'Arquitectura de software',
          desc: 'Diseñamos la estructura de tu sistema antes de escribir la primera línea: diagramas de componentes, despliegue, secuencia y planificación técnica.',
          li: ['Diagramas de componentes, secuencia y despliegue', 'Microservicios, monolitos y arquitectura en capas', 'Planificación técnica documentada'] },
        { icon: 'database', title: 'Bases de datos',
          desc: 'Modelado relacional y NoSQL desde cero: diagramas ER, modelo físico, normalización y consultas optimizadas para sistemas de alta carga.',
          li: ['Modelado ER, físico y relacional', 'PostgreSQL, MySQL, MongoDB, Redis', 'Optimización de queries e índices'] },
        { icon: 'network', title: 'Hardening de redes',
          desc: 'Configuración segura de infraestructura de red bajo estándar CCNA: routers, switches, firewalls y VPNs protegidos desde la base.',
          li: ['Configuración segura de routers y switches', 'Firewall rules, ACLs y segmentación de redes', 'VPNs, monitoreo y hardening perimetral'] },
        { icon: 'cloud', title: 'Seguridad en cloud',
          desc: 'Auditoría y endurecimiento de entornos AWS: identidades, redes, almacenamiento y trazabilidad configurados para resistir ataques.',
          li: ['Revisión de IAM roles y políticas', 'Segmentación VPC y grupos de seguridad', 'S3 policies, CloudTrail y alertas de auditoría'] },
      ],
    },
    process: {
      label: '02 — proceso', title: 'DevSecOps: seguridad en cada vuelta.',
      sub: 'Nuestro ciclo integra seguridad en las 8 fases del desarrollo — no como auditoría final, sino como parte del flujo.',
      steps: [
        { n: 'Planificar', d: 'Modelado de amenazas desde el diseño' },
        { n: 'Codificar', d: 'Revisión de código y prácticas seguras' },
        { n: 'Construir', d: 'Dependencias verificadas y firmadas' },
        { n: 'Probar', d: 'SAST/DAST + pentesting interno' },
        { n: 'Lanzar', d: 'Gates de seguridad antes de cada release' },
        { n: 'Desplegar', d: 'Infraestructura endurecida (hardening)' },
        { n: 'Operar', d: 'Gestión de accesos y secretos' },
        { n: 'Monitorear', d: 'Alertas, logs y respuesta a incidentes' },
      ],
    },
    project: {
      label: '03 — i+d', tag: 'En desarrollo · acceso anticipado',
      title: 'Cumplimiento Ley 21.719, automatizado.',
      desc: 'Estamos construyendo un agente de cumplimiento que evalúa, documenta y monitorea la adecuación de tu empresa a la nueva ley chilena de protección de datos personales — con tus datos siempre en tu infraestructura.',
      points: ['Datos 100% locales: nada sale de tu empresa', 'Evidencia y reportes auditables', 'Monitoreo continuo de brechas normativas'],
      cta: 'Quiero acceso anticipado',
      cdLabel: 'para la entrada en vigencia de la ley', cdDate: '01 · DIC · 2026',
      cdUnits: ['días', 'horas', 'min'],
    },
    team: {
      label: '04 — equipo', title: 'Los fundadores.',
      sub: 'Un perfil construye, el otro ataca. Juntos cubren el ciclo completo.',
      members: [
        { ini: 'EC', name: 'Emilio Castillo', role: 'Co-fundador · Tech Lead',
          bio: 'Arquitectura y desarrollo full-stack. Estudiante de Ingeniería Civil Informática (UNAB). Lidera la construcción de cada plataforma: del diseño del sistema al despliegue.',
          chips: ['Next.js / Node.js', 'PostgreSQL / Supabase', 'Docker / Linux', 'IA aplicada'], certs: [] },
        { ini: 'CR', name: 'Cristóbal', role: 'Co-fundador · Security Lead',
          bio: 'Especialista en seguridad ofensiva y defensiva. Consultorías de seguridad y protección de la información en el rubro minero.',
          chips: [], certs: ['eJPT', 'eWPTX · en curso', 'CCNA', 'AWS Cloud Practitioner'] },
      ],
    },
    quotes: {
      label: '05 — clientes', title: 'Confían en RawSec.',
      items: [
        { q: 'La experiencia 360° cambió la forma en que mostramos los terrenos. Los clientes recorren el proyecto sin moverse de su casa.', who: 'Equipo comercial', org: 'Mar y Cielo · inmobiliaria' },
        { q: 'Necesitaba presencia digital profesional y el resultado fue impecable, en tiempo y forma.', who: 'Psicóloga clínica', org: 'Consulta privada · Santiago' },
        { q: 'Automatizaron el flujo entre nuestro software de gestión y el SII, además de estructurar dos años de datos contables con claridad. Trabajo riguroso y de alto impacto.', who: 'Gerencia', org: 'Inmobiliaria Dominga Norte · La Serena' },
      ],
      clientsStrip: ['KikiBrows · LMS & e-commerce', 'Mar y Cielo · Inmobiliaria', 'Landing Portafolio Psicológia · La Serena', 'Dominga Norte · Finanzas'],
    },
    contact: {
      label: '06 — contacto', title: '¿Conversamos?',
      sub: 'Cuéntanos qué necesitas construir — o qué necesitas proteger. Respondemos dentro de 24 horas.',
      cta1: 'Agendar reunión', copied: '✓ copiado',
      mailSubject: 'Reunión — RawSec Solutions',
    },
    footer: {
      tagline: 'Desarrollo seguro desde Santiago, Chile.',
      rights: '© 2026 RawSec Solutions',
      links: [{ label: 'GitHub', href: 'https://github.com/RawSecSolutions' }, { label: 'rawsecsolutions@gmail.com', href: 'mailto:rawsecsolutions@gmail.com' }],
    },
  },

  en: {
    nav: { links: [
      { id: 'servicios', label: 'Services' },
      { id: 'proceso', label: 'Process' },
      { id: 'proyecto', label: 'R&D' },
      { id: 'equipo', label: 'Team' },
      { id: 'clientes', label: 'Clients' },
    ], cta: 'Book a meeting' },
    hero: {
      eyebrow: 'Secure development · Pentesting · Compliance',
      h1a: ['Software born', 'secure.'],
      h1b: 'Security and development, no compromises.',
      h1c: ['Custom-built.', 'Hardened by design.'],
      sub: 'Full-stack development and cybersecurity audits under one team. We build your platform and harden it — security is never an afterthought.',
      cta1: 'Book a meeting', cta2: 'View services',
      badges: ['eJPT', 'eWPTX · in progress', 'CCNA', 'AWS Cloud Practitioner'],
      term: [
        { t: 'cmd', s: 'rawsec init --client "your-company.com"' },
        { t: 'ok', s: '✓ stack: next.js + postgresql' },
        { t: 'cmd', s: 'rawsec audit --scope web,api,network' },
        { t: 'out', s: '  scanning attack surfaces…' },
        { t: 'ok', s: '✓ 0 critical vulnerabilities' },
        { t: 'cmd', s: 'rawsec deploy --hardened' },
        { t: 'ok', s: '✓ production · monitoring active' },
      ],
      coords: 'SANTIAGO, CHILE · 33.4489°S 70.6693°W',
    },
    strip: ['Full-stack development', 'Certified pentesting', 'Law 21.719 · Chile', 'Cloud architecture', 'Network hardening', 'Automation', 'Machine Learning', 'RAG Agents', 'LLMs', 'Computer Vision', 'Red Team', 'Digital Forensics', 'CCNA Networks', 'AWS Security', 'ISP Systems', 'Payment gateways', 'Financial dashboards', 'Software architecture', 'Database design', 'UML diagrams', 'Data modeling', 'Microservices', 'Server hardening', 'AWS Security', 'Firewall & ACLs', 'Network segmentation', 'IAM & VPC'],
    services: {
      label: '01 — services', title: 'Two disciplines, one team.',
      sub: 'Most teams build first and secure later. We do both at once.',
      items: [
        { icon: 'code', title: 'Custom software',
          desc: 'We build the exact digital solution for your business: web apps, SaaS, e-commerce and integrations on a modern stack.',
          li: ['Web apps and SaaS', 'LMS & e-commerce with local payments', 'API integrations & automation'] },
        { icon: 'shield', title: 'Offensive security',
          desc: 'Audits and pentesting with certified methodology. We find the gaps before an attacker does.',
          li: ['Web & infrastructure pentesting', 'Security audits & hardening', 'Networking (CCNA) & cloud (AWS)'] },
        { icon: 'scale', title: 'Compliance & data',
          desc: 'We get your company ready for Chile\u2019s Law 21.719 on personal data protection, with auditable evidence.',
          li: ['Regulatory gap assessment', 'Data policies & governance', 'Compliance automation'] },
        { icon: 'brain', title: 'Applied AI',
          desc: 'Conversational chatbots, Machine Learning pipelines and RAG agents with local or cloud models.',
          li: ['RAG chatbots with LangChain + ChromaDB', 'Supervised ML classification & prediction', 'Local models (Llama 3) and GPT API'] },
        { icon: 'card', title: 'Payments & Integrations',
          desc: 'Integration of local and international payment gateways, with full checkout and reconciliation flows.',
          li: ['Webpay / Transbank & Banchile Pagos', 'MercadoPago & Getnet REST API', 'Payment flows, refunds & reconciliation'] },
        { icon: 'layers', title: 'Enterprise software',
          desc: 'Complex management systems \u2014 ISP, health, education \u2014 with documented architecture and scalable deployment.',
          li: ['4+1 architecture & SCRUM++', 'WebSocket, Redis & real-time queues', 'NGINX + Docker + Linux (Arch/Ubuntu)'] },
        { icon: 'arch', title: 'Software architecture',
          desc: 'We design your system structure before the first line of code: component, deployment and sequence diagrams plus documented technical planning.',
          li: ['Component, sequence and deployment diagrams', 'Microservices, monoliths and layered architecture', 'Documented technical planning'] },
        { icon: 'database', title: 'Database design',
          desc: 'Relational and NoSQL modeling from scratch: ER diagrams, physical model, normalization and query optimization for high-load systems.',
          li: ['ER, physical and relational modeling', 'PostgreSQL, MySQL, MongoDB, Redis', 'Query and index optimization'] },
        { icon: 'network', title: 'Network hardening',
          desc: 'Secure network infrastructure configuration under CCNA standard: routers, switches, firewalls and VPNs locked down from the ground up.',
          li: ['Secure router and switch configuration', 'Firewall rules, ACLs and network segmentation', 'VPNs, monitoring and perimeter hardening'] },
        { icon: 'cloud', title: 'Cloud security',
          desc: 'AWS environment audit and hardening: identities, networks, storage and traceability configured to resist attacks.',
          li: ['IAM roles and policy review', 'VPC segmentation and security groups', 'S3 policies, CloudTrail and audit alerts'] },
      ],
    },
    process: {
      label: '02 — process', title: 'DevSecOps: security on every loop.',
      sub: 'Our cycle embeds security across all 8 phases of development — not as a final audit, but as part of the flow.',
      steps: [
        { n: 'Plan', d: 'Threat modeling from day one' },
        { n: 'Code', d: 'Code review & secure practices' },
        { n: 'Build', d: 'Verified, signed dependencies' },
        { n: 'Test', d: 'SAST/DAST + internal pentesting' },
        { n: 'Release', d: 'Security gates before every release' },
        { n: 'Deploy', d: 'Hardened infrastructure' },
        { n: 'Operate', d: 'Access & secrets management' },
        { n: 'Monitor', d: 'Alerts, logs & incident response' },
      ],
    },
    project: {
      label: '03 — r&d', tag: 'In development · early access',
      title: 'Law 21.719 compliance, automated.',
      desc: 'We are building a compliance agent that assesses, documents and monitors your company\u2019s alignment with Chile\u2019s new personal data protection law — with your data always on your own infrastructure.',
      points: ['100% local data: nothing leaves your company', 'Auditable evidence & reports', 'Continuous monitoring of compliance gaps'],
      cta: 'Get early access',
      cdLabel: 'until the law takes effect', cdDate: 'DEC · 01 · 2026',
      cdUnits: ['days', 'hours', 'min'],
    },
    team: {
      label: '04 — team', title: 'The founders.',
      sub: 'One profile builds, the other attacks. Together they cover the full cycle.',
      members: [
        { ini: 'EC', name: 'Emilio Castillo', role: 'Co-founder · Tech Lead',
          bio: 'Architecture and full-stack development. Computer Science Engineering student (UNAB). Leads every build: from system design to deployment.',
          chips: ['Next.js / Node.js', 'PostgreSQL / Supabase', 'Docker / Linux', 'Applied AI'], certs: [] },
        { ini: 'CR', name: 'Cristóbal', role: 'Co-founder · Security Lead',
          bio: 'Offensive and defensive security specialist. Security consulting and information protection in the mining industry.',
          chips: [], certs: ['eJPT', 'eWPTX · in progress', 'CCNA', 'AWS Cloud Practitioner'] },
      ],
    },
    quotes: {
      label: '05 — clients', title: 'They trust RawSec.',
      items: [
        { q: 'The 360° experience changed how we showcase our land plots. Clients tour the project from home.', who: 'Sales team', org: 'Mar y Cielo · real estate' },
        { q: 'I needed a professional digital presence and the result was flawless, on time and on point.', who: 'Clinical psychologist', org: 'Private practice · Santiago' },
        { q: 'They automated the flow between our management software and the tax authority, and structured two years of accounting data with clarity. Rigorous, high-impact work.', who: 'Management', org: 'Inmobiliaria Dominga Norte · La Serena' },
      ],
      clientsStrip: ['KikiBrows · LMS & e-commerce', 'Mar y Cielo · Real estate', 'Psychology practice · Santiago', 'Dominga Norte · Finance'],
    },
    contact: {
      label: '06 — contact', title: 'Let\u2019s talk.',
      sub: 'Tell us what you need to build — or what you need to protect. We reply within 24 hours.',
      cta1: 'Book a meeting', copied: '✓ copied',
      mailSubject: 'Meeting — RawSec Solutions',
    },
    footer: {
      tagline: 'Secure development from Santiago, Chile.',
      rights: '© 2026 RawSec Solutions',
      links: [{ label: 'GitHub', href: 'https://github.com/RawSecSolutions' }, { label: 'rawsecsolutions@gmail.com', href: 'mailto:rawsecsolutions@gmail.com' }],
    },
  },
};

export const RAWSEC_EMAIL = 'rawsecsolutions@gmail.com';