// RawSeccopy
export const RAWSEC_DATA = {
  nav: { links: [
    { id: 'equipo', label: 'Perfiles' },
    { id: 'proyectos', label: 'Proyectos' },
    { id: 'proceso', label: 'DevSecOps' },
    { id: 'servicios', label: 'Servicios' },
    { id: 'herramientas', label: 'Herramientas' },
    { id: 'contacto', label: 'Contacto' },
  ], cta: 'Agendar reunión' },
  hero: {
    eyebrow: 'Empresa de software & ciberseguridad · Santiago, Chile',
    h1a: ['Software que nace', 'seguro.'],
    h1b: 'Seguridad y desarrollo sin concesiones.',
    h1c: ['Construido a medida.', 'Blindado por diseño.'],
    sub: 'Desarrollamos plataformas a medida con arquitectura segura. Y si ya tienes un sistema, nuestro equipo de ciberseguridad lo somete a pentesting y auditorías certificadas. Dos especialidades, una sola agencia para cubrir todo tu ciclo digital.',
    cta1: 'Agendar reunión', cta2: 'Ver proyectos',
    badges: ['eJPT', 'eWPTX', 'CCNA', 'AWS Cloud Practitioner'],
    term: [
      { t: 'cmd', s: 'rawsec init --cliente "tu-empresa.cl"' },
      { t: 'ok', s: '✓ stack: next.js + postgresql' },
      { t: 'cmd', s: 'rawsec audit --scope web,api,red' },
      { t: 'out', s: '  escaneando superficies de ataque…' },
      { t: 'ok', s: '✓ 0 vulnerabilidades críticas' },
      { t: 'cmd', s: 'rawsec deploy --hardened' },
      { t: 'ok', s: '✓ producción · monitoreo activo' },
    ],
    coords: 'SANTIAGO, CHILE · 33.4489°S 70.6693°W',
  },
  strip: ['Desarrollo full-stack', 'Pentesting certificado', 'Ley 21.719 · Chile', 'Arquitectura cloud', 'Hardening de redes', 'Automatización', 'Machine Learning', 'Agentes RAG', 'LLMs', 'Visión computacional', 'Red Team', 'Forense digital', 'CCNA · Redes', 'AWS Security', 'Sistemas ISP', 'Pasarelas de pago', 'Dashboards financieros', 'Arquitectura de software', 'Diseño de bases de datos', 'Diagramas UML', 'Modelado relacional', 'Microservicios', 'Hardening de servidores', 'Seguridad AWS', 'Firewall & ACLs', 'Segmentación de redes', 'IAM & VPC'],
  services: {
    label: '05 — Servicios', title: 'Dos especialidades. Un equipo.',
    sub: 'Un perfil construye la plataforma. El otro la ataca y la asegura. Desarrollo y seguridad en paralelo, no como etapas separadas.',
    items: [
      { icon: 'code', title: 'Desarrollo de software a medida',
        desc1: 'Construimos tu plataforma de cero',
        desc2: 'Apps web / móvil, Sistemas de gestión de aprendizaje, e-commerce, portafolios, integraciones con APIs externas, dashboards y analítica de datos. Desde el diseño hasta el despliegue en producción.',
        li: ['Plataformas web y SaaS', 'LMS, e-commerce y pasarelas de pago', 'Integraciones, IA y automatización'] },
      { icon: 'shield', title: 'Ciberseguridad certificada',
        desc1: 'Pentesting y auditorías con metodología certificada.',
        desc2: 'Encontramos las vulnerabilidades antes que un atacantey entregamos el reporte para cerrarlas.',
        li: ['Pentesting web, API e infraestructura', 'Auditorías de red y cloud (AWS)', 'Hardening y cumplimiento normativo'] },
    ],
  },
  process: {
    label: '04 — DevSecOps', title: 'Seguridad en cada vuelta.',
    sub: 'Para proyectos de misión crítica, ofrecemos un ciclo de desarrollo donde la auditoría ofensiva ocurre en paralelo a la construcción. Tu software nace auditado.',
    steps: [
      { n: 'Planificar', d: 'Modelado de amenazas desde el diseño' },
      { n: 'Codificar', d: 'Revisión de código y prácticas seguras' },
      { n: 'Construir', d: 'Dependencias verificadas y firmadas' },
      { n: 'Probar', d: 'SAST/DAST + pentesting interno' },
      { n: 'Lanzar', d: 'Gates de seguridad antes de cada release' },
      { n: 'Desplegar', d: 'Infraestructura endurecida (hardening)' },
      { n: 'Operar', d: 'Gestión de accesos y secretos' },
      { n: 'Monitorear', d: 'Alertas, logs y respuesta a incidentes' },
    ],
  },
  project: {
    label: '06 — Herramientas I+D', tag: 'En desarrollo · acceso anticipado',
    title: 'Cumplimiento Ley 21.719, automatizado.',
    desc: 'Estamos construyendo un agente de cumplimiento que evalúa, documenta y monitorea la adecuación de tu empresa a la nueva ley chilena de protección de datos personalescon tus datos siempre en tu infraestructura.',
    points: ['Datos 100% locales: nada sale de tu empresa', 'Evidencia y reportes auditables', 'Monitoreo continuo de brechas normativas'],
    cta: 'Quiero acceso anticipado',
    cdLabel: 'para la entrada en vigencia de la ley', cdDate: '01 · DIC · 2026',
    cdUnits: ['días', 'horas', 'min'],
  },
  team: {
    label: '01 — Perfiles', title: 'Los fundadores.',
    sub: 'Un perfil construye, el otro ataca. Juntos cubren el ciclo completo.',
    members: [
      { ini: 'EC', name: 'Emilio Castillo Schmidt', role: 'Co-fundador · Jefe de Desarrollo de Software',
        bio: 'Arquitectura y desarrollo full-stack. Estudiante de Ingeniería Civil Informática (UNAB). Lidera la construcción de cada plataforma: del diseño del sistema al despliegue.',
        chips: ['TypeScript / Next.js / NestJS', 'Python / Machine Learning', 'SQL / PostgreSQL', 'IA Generativa (LLMs, RAG)'], certs: [] },
      { ini: 'CR', name: 'Cristóbal Aracena García', role: 'Co-fundador · Jefe de Seguridad de la Información',
        bio: 'Especialista en seguridad ofensiva y defensiva. Estudiante de Bachelor in Computer Science. Pentesting, auditorías de red y administración de infraestructura corporativa.',
        chips: [], certs: ['eJPT', 'eWPTX', 'CCNA', 'AWS Cloud Practitioner'] },
    ],
  },
  quotes: {
    label: '02 — Proyectos', title: 'Lo que hemos hecho.',
    sub: 'Proyectos reales con clientes reales.',
    cases: [
      { client: 'KikiBrows', type: 'LMS & e-commerce',
        org: 'Academia de estética · La Serena',
        what: 'Plataforma educativa completa: cursos por módulos, evaluaciones (quiz, desarrollo escrito y entrega de video), gestión de alumnas, agenda de consultas integrada con Zoom y tienda con pago BanChile.',
        link: { label: 'Ver plataforma', href: 'https://kikibrows.cl', external: true } },
      { client: 'Mar y Cielo', type: 'Experiencia inmersiva 360°',
        org: 'Inmobiliaria · La Serena',
        what: 'Recorrido virtual interactivo para que los compradores recorran los terrenos y proyectos desde cualquier dispositivo, sin necesidad de visita presencial.',
        link: { label: 'Contactar', href: '#contacto', external: false } },
      { client: 'Dominga Norte', type: 'Integración SII & datos contables',
        org: 'Inmobiliaria · La Serena',
        what: 'Automatización del flujo entre el software de gestión interno y el SII. Estructuración y limpieza de dos años de datos contables para reporting claro.',
        link: { label: 'Contactar', href: '#contacto', external: false } },
      { client: 'Minox', type: 'Control de accesos y dominio corporativo',
        org: 'Empresa · Cuarta Región',
        what: 'Registro del dominio corporativo y configuración de cada usuario con permisos específicos por rol. Todo el equipo centralizado en un solo directorio.',
        link: { label: 'Contactar', href: '#contacto', external: false } },
      { client: 'Consulta privada', type: 'Presencia digital profesional',
        org: 'Psicóloga clínica · La Serena',
        what: 'Sitio web profesional para consulta de psicología clínica: presentación de servicios, información de contacto y agendamiento.',
        link: { label: 'Contactar', href: '#contacto', external: false } },
    ],
    clientsStrip: ['KikiBrows · LMS & e-commerce', 'Mar y Cielo · Inmobiliaria', 'Consulta privada · La Serena', 'Dominga Norte · Finanzas', 'Minox · Control de accesos & dominio'],
  },
  ecosystem: {
    label: '07 — Ecosistema RawSec',
    title: 'Más de la marca.',
    items: [
      { name: 'Herramienta Ley 21.719', tag: 'Acceso anticipado',
        desc: 'Agente de cumplimiento normativo para empresas chilenas. Evalúa, documenta y monitorea tu adecuación a la nueva ley de protección de datos.',
        href: '#herramientas', cta: 'Ver herramienta', external: false },
      { name: 'RawClases', tag: 'Próximamente',
        desc: 'LMS escalable para venta como SaaSconstruido sobre la experiencia de KikiBrows y listo para cualquier tipo de academia o curso online.',
        href: null, cta: 'Próximamente', external: false },
    ],
  },
  contact: {
    label: '08 — Contacto', title: '¿Conversamos?',
    sub: 'Cuéntanos qué necesitas construiro qué necesitas proteger. Respondemos dentro de 24 horas.',
    cta1: 'Agendar reunión', copied: '✓ copiado',
    mailSubject: 'ReuniónRawSec Solutions',
  },
  footer: {
    tagline: 'Desarrollo seguro desde Santiago, Chile.',
    rights: '© 2026 RawSec Solutions',
    links: [{ label: 'GitHub', href: 'https://github.com/RawSecSolutions' }, { label: 'rawsecsolutions@gmail.com', href: 'mailto:rawsecsolutions@gmail.com' }],
  },
};

export const RAWSEC_EMAIL = 'rawsecsolutions@gmail.com';
